version: "2.2"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./psql_data:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5435:5432"

  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

